version: 2.0

jobs:
  checkout:
    docker:
      - image: buildpack-deps:trusty
    working_directory: proto_workspace
    steps:
      - checkout

  build_ruby:
    docker:
      - image: buildpack-deps:trusty
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: "circle"
          POSTGRES_DB: proto
          POSTGRES_PASSWORD: "password"
      - image: redis:3.2


    working_directory: proto_workspace
    steps:
      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle

      - run:
          name: Generate database.yml
          command: mkdir -p config

      - run:
          name: echo test
          command: |
            echo 'test:
              adapter: postgresql
              database: proto
              username: "circle"
              host: localhost' > config/database.yml

      - run:
          name: Wait for DB
          command: timeout 15 bash -c 'while ! echo exit | nc localhost 5432; do sleep 10; done'

      - run:
          name: rake db:create db:schema:load
          command: bundle exec rake db:create db:schema:load --trace

      - run:
          name: Test DB migrations
          command: bundle exec rake db:migrate --trace

      - run:
          name: rake test
          command: bundle exec rake test

      - run:
          name: Run Rubocop
          command: bundle exec rake rubocop

      - run:
          name: brakeman
          command: ./script/brakeman.sh


      - persist_to_workspace:
          root: proto_workspace
          paths:
            - vendor/bundle
  build_node:
      docker:
        - image: buildpack-deps:trusty
      working_directory: proto_workspace
      steps:

        - run:
            name: npm rebuild node-sass
            command: npm rebuild node-sass

        - run:
            name: Run NPM Install
            command: npm install

        - run:
            name: Run NPM RUN build
            command: npm run build

        - persist_to_workspace:
            root: proto_workspace
            paths:
              - node_modules
              - config/webpack.json
              - public/*

  deploy_image_prod:
    docker:
      - image: buildpack-deps:trusty
    working_directory: proto_workspace
    steps:
      - attach_workspace:
          at: proto_workspace

      - run:
          name: push to Heroku
          command: git push git@heroku.com:proto.git $CIRCLE_SHA1:refs/heads/master

workflows:
  version: 2
  build:
    jobs:
      one:
        docker:
          - image sidmohan/ruby-ci-2.3.1
        steps:
          - checkout
          - run: mkdir -p proto_workspace
       - persist_to_workspace:
            root: proto_workspace
            paths:
              - node_modules
              - config/webpack.json
              - public/*
          - build_ruby:
              requires:
                - checkout
          - deploy_master:
              filters:
                branches:
                  only:
                    - master
              requires:
                - build_ruby
                - build_node
